---
cluster: "{{ cluster_name }}"
attributes:
  bc_num_hours:
    value: 1

  bc_num_slots:
    label: Number of CPU
    value: 1
    min: 1
    max: 24
    step: 1

  bc_num_mems:
    widget: "number_field"
    label: Memory per CPU (GB)
    value: 4
    min: 1
    max: 128
    step: 1

  bc_partition:
    widget: select
    label: Partition
    options:
      - [ "low", "low" ]

  version:
    widget: select
    label: "MATLAB version"
    help: "This defines the version of MATLAB you want to load."
    options:
      - [ "R2012a", "rc/matlab/R2012a" ]
      - [ "R2013a", "rc/matlab/R2013a" ]
      - [ "R2015a", "rc/matlab/R2015a" ]
      - [ "R2015b", "rc/matlab/R2015b" ]
      - [ "R2016a", "rc/matlab/R2016a" ]
      - [ "R2016b", "rc/matlab/R2016b" ]
      - [ "R2017a", "rc/matlab/R2017a" ]
      - [ "R2017b", "rc/matlab/R2017b" ]
      - [ "R2018a", "rc/matlab/R2018a" ]
form:
  - version
  - bc_num_hours
  - bc_partition
  - bc_num_slots
  - bc_num_mems
  - bc_email_on_started
