- name: matlab directory
  file:
    path: /var/www/ood/apps/sys/matlab
    state: directory

- git:
    repo: 'https://github.com/OSC/bc_osc_matlab.git'
    dest: /var/www/ood/apps/sys/matlab/
    clone: yes

- name: Replace form.yml
  template:
    src: form.yml
    dest: /var/www/ood/apps/sys/matlab/form.yml

- name: Replace form submission template
  copy:
    src: submit.yml
    dest: /var/www/ood/apps/sys/matlab/submit.yml.erb
