---
- hosts: ood
  roles:
    - { name: 'prep_ood', tags: 'prep_ood' }
    - { name: 'ood', tags: 'ood' }
    - { name: 'warewulf_sync', tags: 'warewulf_sync' }
    - { name: 'ohpc_slurm_17_11_11', tags: 'ohpc_slurm_17_11_11', when: slurm_update }
    - { name: 'ood_firewall_and_services', tags: 'ood_firewall_and_services' }
    - { name: 'ohpc_firewall_and_services', tags: 'ohpc_firewall_and_services' }
