---
- name: Creates directory to clone ohpc user create
  file:
    path: "{{ user_create_scripts_path }}"
    state: directory

- name: Clone template repo from upstream
  git:
    repo: "{{ user_create_script_repo }}"
    dest: "{{ user_create_scripts_path }}"

- name: Commands access for Next Sudo
  lineinfile:
    dest: /etc/sudoers
    insertafter: EOF
    line: "{{ RegUser_app_user }} ALL= NOPASSWD: {{ user_create_scripts_path }}/user_create"
    state: present

