---
- name: Create RegUser - {{ RegUser_app_user }} on OHPC
  user:
    name: "{{ RegUser_app_user }}"
    comment: "{{ RegUser_app_user_full_name }}"
    shell: /bin/bash
    createhome: yes
    home: /home/{{ RegUser_app_user }}
    state: present

- name: Create Cluster keys for RegUser - {{ RegUser_app_user }} on OHPC
  script: /usr/bin/cluster-env
  become_user: "{{ RegUser_app_user }}"
