- name: install the latest version of libXtst
  yum:
    name: libXt
    state: latest

- file: Create directory
    path: "{{ matlab_clustershare }}"
    state: directory
    mode: 0755

- name: Download matlab
  get_url:
    url: "{{ matlab_download_url }}"
    dest: "{{ matlab_destination  }}"

- name: Extract matlab
  unarchive:
    src: "{{ matlab_destination  }}"
    dest: "{{ matlab_clustershare }}"

- file: Create directory
    path: "{{ matlab_module_dir }}"
    state: directory
    mode: 0755

- name: Copy modulefile from template to /export/eb/modules/all/matlab/ 
  template:
    src: r2018a
    dest: "{{ matlab_module  }}"
