- name: install the latest version of libXtst
  yum:
    name: libXt
    state: latest

- name: Download matlab
  get_url:
    url: "{{ matlab_download_url }}"
    dest: "{{ matlab_destination  }}"

- name: Extract matlab
  unarchive:
    src: "{{ matlab_destination  }}"
    dest: "{{ matlab_clustershare }}"

- file: Create directory
    path: /export/eb/modules/all/matlab
    state: directory
    mode: 0755

- name: Copy modulefile from files to /export/eb/ 
  file:
    src: r2018a
    dest: /export/eb/modules/all/matlab/r2018a
