---
- name: Enable the Software Collections repository
  yum:
    name: "centos-release-scl"
    state: present

- name: Add Open OnDemand’s repository hosted by the Ohio Supercomputer Center
  yum:
    name: "https://yum.osc.edu/ondemand/1.3/ondemand-release-web-1.3-1.el7.noarch.rpm"
    state: present

- name: Install OnDemand and all of its dependencies
  yum:
    name: "ondemand"
    state: present

- name: Get OpenHPC repo
  yum: name={{ openhpc_release_rpm }} state=present update_cache=true


- name: Install dependencies-nfs-utils, ohpc packages, ntp and other required tools.
  yum: name={{ item }} state=installed update_cache=true
  with_items:
    - nfs-utils
    - ohpc-base-compute
    - ohpc-slurm-client
    - zsh
    - git
    - vim
    - tmux
    - ruby

- name: Mount /home, /opt/ohpc/pub from OHPC node
  lineinfile:
    path: /etc/fstab
    line: '{{ item }}'
  with_items:
    - "{{ headnode_private_ip }}:/home /home nfs nfsvers=3,nodev,nosuid,noatime 0 0"
    - "{{ headnode_private_ip }}:/opt/ohpc/pub /opt/ohpc/pub nfs nfsvers=3,nodev,noatime 0 0"

- name: Create cluster.d directory
  file:
    path: /etc/ood/config/cluster.d
    state: directory

- name: Add cluster configuration files
  template:
    src: cluster.yml
    dest: /etc/ood/config/cluster.d/{{ cluster_name }}.yml

- name: Create interactive desktop settings directory
  file:
    path: /etc/ood/config/apps/bc_desktop
    state: directory

- name: Add interactive desktop settings
  template:
    src: bc_desktop/cluster.yml
    dest: /etc/ood/config/apps/bc_desktop/{{ cluster_name }}.yml

- name: Stage http authz file for ood
  copy:
    src: htpasswd
    dest: /opt/rh/httpd24/root/etc/httpd/.htpasswd
    owner: root
    group: root
    mode: 0644

- name: start and enable slurmd
  service: 
    name: slurmd
    state: started
    enabled: yes

- name: Enable http service
  systemd:
    state: started
    name: httpd24-httpd
    enabled: yes

- name: Open port http/s
  firewalld:
    service: http
    permanent: true
    state: enabled

-  firewalld:
    service: https
    permanent: true
    state: enabled

- name: Disable SELinux Enforcement (permissive)
  selinux:
    policy: permissive
    state: permissive

- name: Set SELinux to permissive mode without reboot
  command: setenforce 0
